### ISSUE TITLE
"Adminer" fürs Backend

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/wuensche_ideen#2]
Das gibt es auch noch als 4er Addon

https://github.com/jdlx/mysql_tools

--
https://www.adminer.org/de/

**Comment by schuer** [comment]
Wofür möchte man sowas haben? Also warum innerhalb REDAXOs statt als Standalone?

**Comment by olien** [comment]
Weil ich keine Lust habe immer die Zugangsdaten raussuchen zu müssen und nicht vergessen will die adminer.php vom Server zu löschen :-))

**Comment by polarpixel** [comment]
Ich nutze das auch sehr gern. Überaus praktisch!

**Comment by gharlan** [comment]
-> https://github.com/FriendsOfREDAXO/adminer

**Comment by schuer** [comment]
This issue was moved to FriendsOfREDAXO/Info#6
