### ISSUE TITLE
FOR addons in den redaxo.org news "bewerben"

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/wuensche_ideen#3]
Sollten wir neue addons von FOR auf redaxo.org in den news anteasern?

Sollte die grundidee hinter FOR ebenfalls erläutert werden für die Öffentlichkeit?

**Comment by olien** [comment]
Wäre doch gut das am Redaxo Tag zu präsentieren. Also Dirk. War ja seine Idee :-)
Oder?

**Comment by schuer** [comment]
Wir hatten im Chat überlegt, FOR bis zum REDAXO-Tag noch nicht allzu öffentlich zu behandeln, damit wir es dort erstmalig vorstellen — und vor allem gemeinsam diskutieren — können.

(Vermutlich hat es inzwischen schon ein großer Teil der aktiven REDAXO-Community mitbekommen, aber egal.)

**Comment by schuer** [comment]
This issue was moved to FriendsOfREDAXO/Info#7
