### ISSUE TITLE
Suche/Search

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/wuensche_ideen#4]
REDAXO 5 benötigt noch eine Suche. Es gibt aktuell verschiedene Vorschläge oder Ansätze:

* RexSearch wird von @xong eventuell für R5 entwickelt
* @phoebusryan möchte vielleicht einen Crawler bauen
* Auf Basis von @tbaddade s Watson könnte eine schlichte Suche fürs Frontend gebaut werden
* Eine Anregung für eine simple Suche hat @tbaddade mal in ein [Gist](https://gist.github.com/tbaddade/575ddf218ba2b733caa30292c354ce38) gesteckt

Vielleicht könnten die verschiedenen Kräfte hier bei FOR gebündelt und eine Suche entwickelt werden.

**Comment by phoebusryan** [comment]
Ich hatte schon ein paar Stunden in meinen rex_sphider investiert und hatte auch schon viele Zeilen gecodet aber aufgrund der Aussage von @xong (er würde rex_search bis Ende Mai portieren) habe ich das Projekt eingestellt, da ich absolut gegen Parallelentwicklung und Manpowerverschwendung bin.

**Comment by olien** [comment]
Ideen

- Berücksichtigung von TableManager Tabellen
- Berücksichtigung der Community Berechtigungen
- PDFs berücksichtigen

**Comment by phoebusryan** [comment]
Mein Sphider wird PDFs berücksichtigen, Tabellen aber nicht. Geschützte Bereiche sicher in einem zweiten Schritt.

**Comment by alexplusde** [comment]
Mir wären Auswertungen sehr wichtig, um mehr über die Erwartungen der Nutzer zu erfahren.

In rex_search wurde bspw. gezeigt, welche die häufigsten Suchbegriffe waren und ob Treffer für den Begriff vorhanden sind.

Außerdem ergänzend zu @olien: 

- Cronjobs, automatische Aktualisierung des Suchindex, wenn sich Tabelleninhalte von yform ändern.
- Basis-Klassen fürs Froentend (z. B. Suchergebnis-Paginierung)

**Comment by schuer** [comment]
This issue was moved to FriendsOfREDAXO/Info#8
