### ISSUE TITLE
Analytics (Google/Piwik)

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/wuensche_ideen#5]
Nur als Idee in den Raum geworfen. Vielleicht hat ja jemand Motivation, sowas umzusetzen:

Wie wäre es mit einem generischen Analytics-Addon, das ein paar schlichte Zahlen im REDAXO-Backend zeigt und Kurven dazu malt? Es müsste auf die APIs der beiden wichtigsten Tracker —  Google und Piwik — zugreifen, und es sollte sicherlich auch in der Lage sein, die Tracking-Codes in verschiedenen Ausführungen in die Website zu injizieren.

Wir haben damals den [Piwik Tracker für R4](https://github.com/skerbis/redaxo_piwik_tracker-rex4) gemacht, der inzwischen von @skerbis gepflegt wird. Sowas in der Art und mit zusätzlichem Support für Google Analytics fände ich klasse. Was meint ihr?

**Comment by polarpixel** [comment]
Gute Anregung.
Von @phoebusryan gibt's ja schon das hier:
https://github.com/phoebusryan/rex_analytics

**Comment by phoebusryan** [comment]
Das war mal geplant.. ganz kurz aber da GA und Piwik ganz anders funktionieren (das eine ist selfhosted, das andere ist bei google) ... wurde das wieder gecancelt.

https://github.com/phoebusryan/rex_analytics/issues/5
https://github.com/skerbis/redaxo_piwik_tracker-rex4/issues/8

Was es aber wenn irgendwie möglich geben wird, ist eine Ausgabe im Backend für GA:
https://github.com/phoebusryan/rex_analytics/issues/6

**Comment by schuer** [comment]
@phoebusryan Beide haben aber eine API, die angesprochen werden kann, um ein paar Kernzahlen zu holen und ins REDAXO zu malen. Das wäre für mich das Key-Feature, weil danach immer wieder Kund*innen fragen.

Das Einbringen der Tracking-Codes finde ich nett, ginge aber auch von Hand.

**Comment by phoebusryan** [comment]
Ja, siehe hier:
https://github.com/phoebusryan/rex_analytics/issues/6

Das wird also definitiv kommen.

**Comment by skerbis** [comment]
Sehr geehrte Kunden, 

vom 14.05.2016 bis einschließlich 29.05.2016 bin ich nicht im Büro. 
Ihre E-Mail kann daher leider erst nach meiner Rückkehr bearbeitet werden.

In dringenden Fällen wenden Sie sich bitte an die Zentrale unter
0 28 41 / 88 99 98 - 0 oder per E-Mail an info@klxm.de. 

- Eingehende E-Mails werden nicht weitergeleitet! 

Mit freundlichen Grüßen

Thomas Skerbis


________________________________________________________________


KLXM Crossmedia GmbH
Haagstraße 11      
D-47441 Moers 

Tel.: (0 28 41) 88 99 98-0    
Fax: (0 28 41) 88 99 98-9    
eMail:  info@klxm.de
http://www.klxm.de
     
________________________________________________________________

Angaben nach EHUG vom 10.11.2006:
HRB Kleve 5856
Geschäftsführer:  Christian Hommel · Achim Müntel · Thomas Skerbis

Ihre Daten werden elektronisch gespeichert und verarbeitet (Hinweis nach § 33 BDSG)

**Comment by schuer** [comment]
This issue was moved to FriendsOfREDAXO/Info#9
