### ISSUE TITLE
Custom Addon

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/wuensche_ideen#7]
Hallo,

ich glaube Gregor hatte die Idee ein Custom-Addon / Projekt-Addon zu entwicklen in dem jeder Entwickler, jedes Team seine eigene Klassen / Assets (projektspezifisch / firmenspezifisch) verwalten kann.

Diese "eigenen" Daten sollten natürlich bei einem Update nicht verloren gehen.

@gharlan hat vielleicht mehr Infos hierzu...  :-)

LG
Oliver

**Comment by gharlan** [comment]
Siehe https://github.com/redaxo/redaxo/issues/688

Sehe das auch eher dort, also direkt bei Redaxo, nicht hier bei den Friends, da ich es eben direkt mit ausliefern würde.

**Comment by olien** [comment]
Ok. Hatte das Issue nicht mehr gefunden...

**Comment by schuer** [comment]
This issue was moved to FriendsOfREDAXO/Info#11
