### ISSUE TITLE
Backend-"Mutter-AddOn"

### ISSUE THREAD

**Issue by polarpixel** [FriendsOfREDAXO/wuensche_ideen#8]
Es gab die Idee schon bei Redaxo 4 hin und wieder:
Ich fände es gut, wenn es für kleine Backend-Helferlein-AddOns ein Mutter-AddOn gäbe, so dass sich diese als Plugin in das AddOn einklinken könnten. Das würde die AddOn-Verwaltung übersichtlicher machen, und im Idealfall würde das Mutter-Addon sogar bestimmte, oft benötigte Funktionalitäten bereitstellen, so dass die Plugins diese mit minimalem Aufwand nutzen könnten, z.B. CSS- oder JS-Dateien laden, etc.

Beispiele für diese kleinen Backend-AddOns wären Sachen wie (man könnte die Liste lange fortsetzen):
- Selectfeld-Replacements wie Harvesthq / Select2
- Datepicker / Iconpicker
- Redaxo-Logo gegen Kunden-Logo ersetzen
- einige der Plugins von oliens Out5-AddOn würden hier auch reinpassen.

**Comment by olien** [comment]
Habe out5 hierhin übertragen... https://github.com/FriendsOfREDAXO/out5

**Comment by schuer** [comment]
… und einen Screenshot in die README bekommen :)

**Comment by olien** [comment]
Top

**Comment by schuer** [comment]
This issue was moved to FriendsOfREDAXO/Info#12
