### ISSUE TITLE
Issues nach »Info« migrieren?

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/wuensche_ideen#9]
Wollen wir die Wünsche und Ideen nicht lieber im Basis-Repo »Info« aufhängen? Dort findet ja jegliche Diskussion zu FOR allgemein statt, und ich finde diese Wünsche-Repo irgendwie überflüssig.

Die Issues könnte man mittels Github API migrieren.

**Comment by gharlan** [comment]
👍

**Comment by polarpixel** [comment]
👍

**Comment by schuer** [comment]
Vielleicht noch @olien s Meinung. Er hatte das Repo angelegt.

**Comment by olien** [comment]
Dafür!

**Comment by schuer** [comment]
This issue was moved to FriendsOfREDAXO/Info#13

**Comment by schuer** [comment]
Fürs Protokoll: Die Verknüpfungen lassen sich bei der Migration leider nicht erhalten, weil Github keine offizielle Funktionalität anbietet, sondern das ganze lediglich über Hilfsmittel über die API passiert wie hier beschrieben: https://github.com/holman/ama/issues/413
